### ISSUE TITLE
پیشنهاد برای بهتر شدن پروژه

### ISSUE THREAD

**Issue by mhb8898** [ErfanPY/aparatPlayListDownloader#1]
سلام
به نظرم ازونجایی که برای این کار ها ابزار معروف تری به اسم youtube-dl وجود داره و این ابزار از آپارات پشتیبانی میکنه و نسخه یوتیوبش قابلیت دانلود پلی لیست داره
خیلی خوب میشد که این کدتو به اون اضافه میکردی تا همه بتونن با  استفاده از همون ابزار که به نسبت جامع تره پلی لیست های آپارات رو دانلود کنن

**Comment by ErfanPY** [comment]
سلام 
تشکر از نظرت
 این پروژه رو به عنوان یک ابزار کوچیک و جمع و جور درست کردم و هدفم بیشتر یادگیری بود
