### ISSUE TITLE
اشتباه تایپی 

### ISSUE THREAD

**Issue by behnambm** [ErfanPY/aparatPlayListDownloader#2]
اسم فایل اصلی اشتباهه :)

**Comment by ErfanPY** [comment]
سلام . کدوم فایل ؟ به نظر درست میاد که.

**Comment by behnambm** [comment]
فایل اصلی باید باشه 
apd.py (aparat playlist downloader)
شایدم من اشتباه میکنم :)

**Comment by ErfanPY** [comment]
کاملا صحیح . تشکر
