### ISSUE TITLE
اسکریپت نصب

### ISSUE THREAD

**Issue by develhopper** [ErfanPY/aparatPlayListDownloader#4]
سلام وقت بخیر پیشنهادم اینه که یه اسکریپت نصب به پروژه اضافه کنید
خودکار بیاد پیشنیاز های پروژه رو چک کنه که نصب هست یا نه اگه نصب نبود نصب کنه
بعدش فایل اصلی رو کپی کنه توی مسیر 
~/.local/bin
و به شرطی که اگر این مسیر داخل متغیر
PATH
بود
بتونیم مستقیما از طریق ترمینال اجراش کنیم
به شکل زیر
![Screenshot_2020-02-29_23-06-20](https://user-images.githubusercontent.com/31121152/75613926-2d0fbb00-5b48-11ea-8421-f3e46abc4055.png)

**Comment by ErfanPY** [comment]
شلام تشکر فراوان . مرج شد
